### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by duckimann** [Ademking/ademking.github.io#4]
Congrats on your new blog 🎉🎉

I've noticed this
![image](https://user-images.githubusercontent.com/46382253/211172751-fcbf1e3f-7dc3-4d11-85d5-1834bafc5d14.png)

It would be better if you move the post title to the left like `Scarping Canva Pro Links | Adem's Dev Journey`, but if you intentionally left it like that then it's fine :D

**Comment by Ademking** [comment]
Hello @duckimann and thank you for your feedback! I'm glad you're enjoying my blog ❤️. As for the post title alignment, I actually intentionally left it as it is.

I will definitely consider making this change in the future.

**Comment by Ademking** [comment]
Fixed [10a3f16](https://github.com/Ademking/ademking.github.io/commit/10a3f16cfa473c61ff668fa2cd2ed19f362b0432)
Thank you again 👍
